### ISSUE TITLE
Spelling/wording in "Getting Started Guide.md"

### ISSUE THREAD

**Issue by Saphieron** [es-ude/ElasticNodeMiddleware#10]
There are some spelling errors/unclear word choices in the [Getting Started Guide](https://github.com/es-ude/ElasticNodeMiddleware/blob/master/docs/GettingStartedGuide.md):

- "The upload script is specialized in the BUILD.bazel in the app folder." specified -> probably meant specialized. 
- "The following photo shows the construction after connecting the whole hardware." Construction -> Setup  and "the whole hardware" -> "all hardware parts"
- "Now you should see perennially string: 'Hello. You debug with Uart.'" -> It should now repeatedly print the string [...]
- "We write some test" -> "we wrote some tests"

**Comment by schielgr** [comment]
fixed - there are some more issues in the file but if you find them, then please just rewrite the parts directly.
