### ISSUE TITLE
Getting Started Guide: Provide example bitfiles for other supported FPGAs

### ISSUE THREAD

**Issue by Saphieron** [es-ude/ElasticNodeMiddleware#13]
The Elastic Node seems to support several Spartan 7 FPGAs, i.e. XC7S6, XC7S15, XC7S25 and XC7S50. However the Getting started guide only provides 2 corresponding bit files for the XC7S15. We should include some dummy blink examples, identical to the S15 one for the other chips and point this out in the guide to be aware what chip is built on their Elastic Node.

**Comment by DerDavidos** [comment]
Vitfiles for S6, S15, S25 and S50 are present and the use of them is pointed out in the CloneGuide.
