### ISSUE TITLE
Writing your own programm guide should describe how to use the Middleware as a library

### ISSUE THREAD

**Issue by Saphieron** [es-ude/ElasticNodeMiddleware#14]
In the [Write your own programm guide](https://github.com/es-ude/ElasticNodeMiddleware/blob/master/docs/WriteOwnProgramGuide.md) it describes how a programmer can write their own code inside the cloned repository code of the Elastic Node Middleware. 
This however would lead to a very complicated versioning and potential code duplication. 

Therefore the proposal would be to restructure the guide so that it starts by using the [Bazel C Project Creator](https://github.com/es-ude/BazelCProjectCreator). Then it should describe all steps, where many are most likely related to configuring bazel, to pull the Middleware as a dependency and use the library APIs.

Some code examples of how to use the Middleware should also be shown for more clarity.
Maybe also include/describe a fitting .gitignore file.

**Comment by glencoe** [comment]
In that regard the part should also contain a copy-pasteable WORKSPACE entry for the elastic node middleware
```
es_github_archive(
  name = "ElasticNodeMiddleware",
  version = "1.0",
)
```
and mention that the dependencies the project is currently tested with are the ones listed in the `ElasticNodeMiddleware/WORKSPACE`, so when in doubt copy the deps from there.
