### ISSUE TITLE
v1.11 does not allow flashing the device do to incompatibility

### ISSUE THREAD

**Issue by Saphieron** [es-ude/ElasticNodeMiddleware#33]
After changes to the controlManager and the char commands it can accept in v1.11, it cannot function anymore with the bit file uploading script, making it impossible to write new bit files to the flash.
Due to an apparent synchronisation required by the python flashing script, it currently expect the default case in the switch statement of the controlManager to respond with an echo+1 of the last received character until synchronisation is complete.
This makes the approach incompatible with the current, simplified, solution to extend the set of char commands by handling all non-default chars in the default case and calling a function pointer there to a user defined function with more cases.

Suggestion is to define a different flash script synchronisation approach. Currently I see two possibilities:
- Changing the way the python script performs the synchronisation, e.g. to a special sequence of characters. This will require some rewrite of the python component.
- Keeping the current synchronisation that requires the default control manager switch case to be the echo + 1. User defined sequences then require a special use case char to enter a "user" command case. E.g pressing 'u' enters the user space and the subsequent character is then handled by a user defined function.

**Comment by DerDavidos** [comment]
temporarily fixed with v1.1.1
