### ISSUE TITLE
elasticnode_fpgaPowerOff() causes issues on new ENs

### ISSUE THREAD

**Issue by mokouMonday** [es-ude/ElasticNodeMiddleware#48]
Sequence 
elasticnode_fpgaPowerOff();
_delay_ms(4000);
elasticnode_fpgaPowerOn();
in main makes the mcu crash (only on new elastic nodes).
After elasticnode_fpgaPowerOff() the Fpga can be turned on only after enabling and disabling the xmem interface.

**Comment by DerDavidos** [comment]
the elasticnode_initFpgaInterface can now be called at start up as shown in the new example main.c
