### ISSUE TITLE
elasticnode_configureFPGA() function contains a endless while loop

### ISSUE THREAD

**Issue by SuperChange001** [es-ude/ElasticNodeMiddleware#49]
Ideally, you can let the FPGA to start configure from any address you want.
```
elasticnode_configureFPGA(0x0); // Configures to address 0x0 at start up
```
However, inside this function, there is a while loop, which waiting for the configuration finish,
```
//wofür?
uint8_t reconfigure_fpgaMultibootComplete_internal(void) {
    return fpgaMultibootCompleteState;
}
```
I even saw a comment before this function.

---
So, by reading the code base, I would assume, if you set an external interrupt properly, the FPGA can notify the MCU when the configuration is DONE, by call `reconfigure_fpgaSetDoneReponse_internal()`.

**Comment by DerDavidos** [comment]
The reconfigure library is reworked, when the reconfiguration has problems (for example a incompatible bitfile is loaded) the reconfiguration is aborted.
